### ISSUE TITLE
Use travis for automated testing

### ISSUE THREAD

**Issue by rasmusbergpalm** [Munter/todomvc-challenge#1]
travis is really easy to get going and integrates beautifully with github (and is free), and you could trivially implement testing your assetgraph against all the MVC TODO's in order to make sure that you don't do regressions etc.

**Comment by Munter** [comment]
Tried to set it up. Did it the same way as all other repos I've set up with Travis. But it doesn't pick up changes. Can't figure out why

**Comment by rasmusbergpalm** [comment]
Maybe you need a master branch. Or try making a pull request
